apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
  labels:
    {{ labels | indent(4) }}
  annotations:
    kubernetes.io/service-account.name: {{ app_name }}