apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ app_name }}
  labels:
    {{ labels | indent(4) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ app_name }}
subjects:
  - kind: ServiceAccount
    name: {{ app_name }}
    namespace: {{ app_namespace }}