apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ main_domain_name }}`)
      middlewares:
        - name: oauth2-proxy-forward-auth
          namespace: auth
        - name: oauth2-proxy-auth-error
          namespace: auth
      services:
        - kind: Service
          name: {{ app_name }}
          port: 3000
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
  tls: {}