- name: noop
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: update os based on os_type
      block:
        - name: update apt-based systems
          apt:
            update_cache: yes
            upgrade: dist
          when: ansible_facts['os_family'] == 'Debian'

        - name: update dnf-based systems
          dnf:
            name: '*'
            state: latest
          when: ansible_facts['os_family'] == 'RedHat'

        - name: update apk-based systems
          apk:
            update_cache: yes
            upgrade: yes
          when: ansible_facts['os_family'] == 'Alpine'

    - name: install all needed packages based on os_type
      block:
        - name: install packages on apt-based systems
          apt:
            name:
              - curl
              - eza
              - git
              - ca-certificates
              - gnupg2
              - lsb-release
              - ubuntu-keyring
              - btop
            state: present
          when: ansible_facts['os_family'] == 'Debian'

        - name: install packages on dnf-based systems
          dnf:
            name:
              - curl
              - git
              - btop
            state: present
          when: ansible_facts['os_family'] == 'RedHat'

        - name: install packages on apk-based systems
          apk:
            name:
              - curl
              - git
              - btop
              - eza
            state: present
          when: ansible_facts['os_family'] == 'Alpine'


    - name: install bash on apk-based systems and set as default shell
      block:
        - name: install bash  
          apk:
            name: bash
            state: present
          when: ansible_facts['os_family'] == 'Alpine'  
        - name: change default shell to bash
          user:
            name: "{{ ansible_facts['env']['SUDO_USER'] | default(ansible_facts['env']['USER']) }}"
            shell: /bin/bash
          when: ansible_facts['os_family'] == 'Alpine'  

    # - name: fix ohmybash if needed
    #   shell: |
    #       if [ -d ~/.oh-my-bash ]; then
    #         cd ~/.oh-my-bash && git reset --hard origin/master && git pull origin master
    #       fi

    - name: install oh-my-bash if not present
      shell:
        cmd: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" "" --unattended
      args:
        creates: ~/.oh-my-bash

    - name: config bashrc
      blockinfile: 
        path: ~/.bashrc
        prepend_newline: yes
        append_newline: yes
        block: |

          export EDITOR=nvim
          
          # disable clock in oh-my-bash
          THEME_SHOW_CLOCK=false

          # eza aliases
          alias l="eza -lah --group-directories-first --icons=auto"
          alias lt="eza -a --tree --level=2 --long --icons --git --group-directories-first"
          alias sl="sudo eza -lah --group-directories-first --icons=auto"
          alias slt="sudo eza -a --tree --level=2 --long --icons --git --group-directories-first"

          # directory aliases
          alias ..="cd .."
          alias ...="cd ../.."
          alias ....="cd ../../.."


    - name: uninstall neovim if installed from package manager
      block:
        - name: remove neovim from apt-based systems
          apt:
            name: neovim
            state: absent
          when: ansible_facts['os_family'] == 'Debian'

        - name: remove neovim from dnf-based systems
          dnf:
            name: neovim
            state: absent
          when: ansible_facts['os_family'] == 'RedHat'

        - name: remove neovim from apk-based systems
          apk:
            name: neovim
            state: absent
          when: ansible_facts['os_family'] == 'Alpine'

    - name: install neovim from official source if not present
      block:
        - name: get and setup binary
          become: true
          shell: |
            curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
            rm -rf /opt/nvim-linux-x86_64
            tar -C /opt -xzf nvim-linux-x86_64.tar.gz
            rm nvim-linux-x86_64.tar.gz 
          args:
            creates: /opt/nvim-linux-x86_64

        - name: symlink nvim binary
          file:
            src: /opt/nvim-linux-x86_64/bin/nvim
            dest: /usr/local/bin/nvim
            state: link

    - name: config neovim
      ansible.builtin.shell:
        cmd: |
          mkdir -p ~/.config/nvim

    - name: nvim init.vim
      copy:
        dest: ~/.config/nvim/init.vim
        content: |
          nnoremap <D-s> :w<cr>
          inoremap <D-s> <esc>:w<cr>i
          vnoremap <D-c> "+y
          nnoremap <D-c> "+yy
          inoremap <D-c> <Esc>"+yya
          nnoremap <D-z> :undo<cr>
          inoremap <D-z> <Esc>:undo<cr>i
          nnoremap <D-y> :redo<cr>
          inoremap <D-y> <Esc>:redo<cr>i

          set clipboard=unnamedplus

          lua << EOF
          vim.g.clipboard = {
            name = "OSC 52",
            copy = {
              ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
              ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
            },
            paste = {
              ["+"] = require("vim.ui.clipboard.osc52").paste("+"),
              ["*"] = require("vim.ui.clipboard.osc52").paste("*"),
            },
          }
          EOF