apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ pgi_name }}
  namespace: {{ app_namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ pgi_name }}
  podMetricsEndpoints:
  - port: metrics


---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-controller-manager
  namespace: cnpg-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
  - port: metrics