- name: create lxc container
  hosts: 'prox-n1'
  gather_facts: false
  vars:
    proxmox_node        : "{{ inventory_hostname }}"
    proxmox_password    : "{{ ansible_password }}"
    container_ssh_file  : "{{ ssh_pub_key_file }}"
    container_hostname  : 'uptime'
    container_vlan_id   : 10
    container_ip        : ''
    container_vmid      : 10008
    container_disk_size : 4
    container_memory    : 1024
    container_cores     : 1
    container_user      : 'root'
    container_mount     : ''
    container_nesting   : 1
    container_mac       : 'BC:24:12:00:10:08'

  tasks:
    # create basic container
    #
    - import_tasks: ../ansible/create-lxc.yaml

    # install docker
    #
    - import_tasks: ../ansible/add-docker.yaml

    ## Uptime Kuma setup
    ##
    - name: create uptime kuma directory
      delegate_to: "{{ container_hostname }}"
      become: yes
      file:
        path: ~/uptime-kuma
        state: directory

    - name: copy docker-compose file
      delegate_to: "{{ container_hostname }}"
      copy:
        dest: ~/uptime-kuma/docker-compose.yaml
        content: "{{ lookup('template', 'docker-compose.yaml') }}"
    
    - name: run uptime kuma container compose up
      delegate_to: "{{ container_hostname }}"
      become: yes
      shell: |
        cd ~/uptime-kuma
        docker compose up -d -y

    # install nginx
    #
    - import_tasks: ../ansible/add-nginx-ubuntu.yaml
      
    ## Nginx
    ##
    - name: create nginx config
      delegate_to: "{{ container_hostname }}"
      copy:
        dest: /etc/nginx/conf.d/{{ container_hostname }}.conf
        content: "{{ lookup('template', 'nginx-upkuma.conf') }}"


    # add certificates and restart nginx
    #
    - import_tasks: ../ansible/add-ssl-certificate.yaml
      vars:
        sites: '-d {{ container_hostname }}.{{ domain_name }}'
        reloadcmd: 'sudo systemctl restart nginx'


    # add connection to local ssh config
    #
    - import_tasks: ../ansible/add-local-ssh-config.yaml
      vars:
        hostname: '{{ container_hostname }}'
        host: '{{ container_hostname }}'