## install local software and config nodes

- name: configure vm
  hosts: 'k8s-nodes'
  tasks: 

    - name: update system
      become: yes
      apt:
        update_cache: yes
        upgrade     : dist
        autoremove  : yes
        autoclean   : yes

    - name: install packages
      become: yes
      ansible.builtin.apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - btop
          - python3-kubernetes
        state: present
        
    - name: Disable swap for current session
      command: swapoff -a

    - name: Remove Swap entry from /etc/fstab
      become: true
      ansible.builtin.lineinfile:
        dest: /etc/fstab
        regexp: swap
        state: absent

    - name: update ip-tables for containerd
      become: true
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf 
        line: "{{ item }}"
        create: yes
      with_items:
        - 'overlay'
        - 'br_netfilter'

    - name: refresh ip drivers
      become: true
      ansible.builtin.command: "{{ item }}"
      with_items: 
        - modprobe overlay
        - modprobe br_netfilter

    - name: Configure sysctl params for Kubernetes.
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf 
        line: "{{ item }}"
        create: yes
      with_items:
        - 'net.bridge.bridge-nf-call-iptables  = 1'
        - 'net.ipv4.ip_forward                 = 1'
        - 'net.bridge.bridge-nf-call-ip6tables = 1'

        # fix too many inotify watches error in grafana alloy
        # 
        - 'fs.inotify.max_user_watches = 524288'
        - 'fs.inotify.max_user_instances = 512'

    - name: Apply sysctl params without reboot
      become: true
      command: sysctl --system

    ## containerd setup, versions see in 0-deploy-cluster.yaml
    ##
    - import_tasks: ./libs/1-install-containerd.yaml

    ## kube setup, version see in 0-deploy-cluster.yaml
    ##
    - import_tasks: ./libs/2-install-k8s-packages.yaml

