

- name: create lxc container
  hosts: 'prox-n2'
  gather_facts: false
  vars:
    proxmox_node        : "{{ inventory_hostname }}"
    proxmox_password    : "{{ ansible_password }}"
    container_ssh_file  : "{{ ssh_pub_key_file }}"
    container_hostname  : 'omada'
    container_vlan_id   : 10
    container_ip        : '192.168.10.7'
    container_vmid      : 10007
    container_disk_size : '8G'
    container_memory    : 2048
    container_cpu       : 1
    container_user      : 'root'
  tasks:
    # create basic container
    #
    - import_tasks: ../ansible/create-lxc.yaml

    ## omada setup
    ##
    - name: setup omada controller
      delegate_to: "{{ container_hostname }}"
      become: yes
      block:
        - name: update system
          apt:
            update_cache  : yes
            upgrade       : dist
            autoremove    : yes
            autoclean     : yes

        - name: install packages
          apt:
            name          : "{{ item }}"
            state         : present
          with_items:
            - openjdk-11-jre-headless
            - autoconf 
            - make 
            - gcc
            - gnupg
            - curl
            - jsvc

        - name: add mongodb repository
          become: yes
          shell: |
            curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
            sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
            --dearmor
            echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          args:
            creates: /etc/apt/sources.list.d/mongodb-org-7.0.list

        - name: update repository cache
          apt:
            update_cache: yes

        - name: install mongodb
          apt:
            name: mongodb-org
            state: present

        - name: enable and start mongodb service
          systemd:
            name: mongod
            state: started
            enabled: yes

        - name: download omada controller
          get_url:
            url: https://static.tp-link.com/upload/software/2025/202501/20250109/Omada_SDN_Controller_v5.15.8.2_linux_x64.deb
            dest: /tmp/Omada_SDN_Controller_v5.15.8.2_linux_x64.deb

        - name: install omada controller
          apt:
            deb: /tmp/Omada_SDN_Controller_v5.15.8.2_linux_x64.deb
            state: present

        - name: start omada controller
          systemd:
            name: omada
            state: started
            enabled: yes
          ignore_errors: yes


    ## Nginx
    ##
    - name: install nginx
      delegate_to: "{{ container_hostname }}"
      apt:
        name: nginx
        state: present

    - name: create nginx config
      delegate_to: "{{ container_hostname }}"
      copy:
        dest: /etc/nginx/conf.d/{{ container_hostname }}.conf
        content: "{{ lookup('template', 'nginx-omada.conf') }}"

    # add certificates and restart nginx
    #
    - import_tasks: ../ansible/add-ssl-certificate.yaml
      vars:
        sites: '-d {{ container_hostname }}.{{ domain_name }}'
        reloadcmd: 'sudo systemctl restart nginx'

    # add connection to local ssh config
    #
    - import_tasks: ../ansible/add-local-ssh-config.yaml
      vars:
        hostname: '{{ container_hostname }}'
        host: '{{ container_hostname }}'