- name: create lxc container
  hosts: 'prox-n2'
  gather_facts: false
  vars:
    proxmox_node        : "{{ inventory_hostname }}"
    proxmox_password    : "{{ ansible_password }}"
    container_ssh_file  : "{{ ssh_pub_key_file }}"
    container_hostname  : 'homepage'
    container_vlan_id   : 40
    container_ip        : ''
    container_vmid      : 40302
    container_disk_size : 3
    container_memory    : 1024
    container_cores     : 1
    container_user      : 'root'
    container_mount     : ''
    container_nesting   : 1

  tasks:
    # create basic container
    #
    - import_tasks: ../ansible/create-lxc.yaml

    # add docker
    #
    - import_tasks: ../ansible/add-docker.yaml

    # copy configs
    #
    - name: create config directory
      delegate_to: "{{ container_hostname }}"
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /config
        - /config/homepage
        - /config/nginx
  
    - name: copy configs
      delegate_to: "{{ container_hostname }}"
      become: true
      copy:
        dest: "{{ item.dest }}"
        force: true
        content: '{{ lookup("template", "{{ item.src }}") }}'
      with_items:
        - { src: 'homepage-nginx.conf', dest: '/config/nginx/nginx.conf' }

    # run container
    #
    - name: run homepage container
      delegate_to: "{{ container_hostname }}"
      become: true
      shell: |
        if [ ! "$(docker ps -a | grep homepage)" ]; then 
          docker run --name homepage \
            -e PUID=1000 \
            -e PGID=1000 \
            -p 3000:3000 \
            -v /config/homepage/config:/app/config \
            -v /var/run/docker.sock:/var/run/docker.sock:ro \
            --restart unless-stopped \
            ghcr.io/gethomepage/homepage:latest
        fi


    - name: run nginx container
      delegate_to: "{{ container_hostname }}"
      become: true
      shell: |
        if [ ! "$(docker ps -a | grep nginx)" ]; then 
          docker run --name nginx \
            -v /config/nginx/nginx.conf:/etc/nginx/nginx.conf \
            -v /usr/ssl:/usr/ssl \
            -p 80:80 \
            -p 443:443 \
            --restart unless-stopped \
            nginx:latest
        fi

    # add certificates and restart nginx
    #
    - import_tasks: ../ansible/add-ssl-certificate.yaml
      vars:
        sites: '-d {{ container_hostname }}.{{ domain_name }}'
        reloadcmd: 'sudo docker restart nginx'


    # add connection to local ssh config
    #
    - import_tasks: ../ansible/add-local-ssh-config.yaml
      vars:
        hostname: '{{ container_hostname }}'
        host: '{{ container_hostname }}'