- name: create lxc container
  hosts: 'prox-n3'
  gather_facts: false
  vars:
    proxmox_node        : "{{ inventory_hostname }}"
    proxmox_password    : "{{ ansible_password }}"
    container_ssh_file  : "{{ ssh_pub_key_file }}"
    container_hostname  : 'home'
    container_vlan_id   : 40
    container_ip        : ''
    container_vmid      : 40206
    container_disk_size : 5
    container_memory    : 1024
    container_cores     : 1
    container_user      : 'root'
    container_mount     : ''
    container_nesting   : 1
    container_mac       : 'BC:24:12:40:02:06'

  tasks:
    # create basic container
    #
    - import_tasks: ../ansible/create-lxc.yaml

    # add docker
    #
    - import_tasks: ../ansible/add-docker.yaml


    - import_tasks: ../ansible/add-nginx-ubuntu.yaml

    # copy configs
    #
    - name: create config directory
      delegate_to: "{{ container_hostname }}"
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - ~/homepage/docker
        - ~/homepage/config
        - ~/homepage/images

    - name: copy configs
      delegate_to: "{{ container_hostname }}"
      become: true
      copy:
        dest: "{{ item.dest }}"
        content: '{{ lookup("template", item.src) }}'
      with_items:
        - { src: 'services.yaml', dest: '~/homepage/config/services.yaml' }
        - { src: 'settings.yaml', dest: '~/homepage/config/settings.yaml' }
        - { src: 'widgets.yaml', dest: '~/homepage/config/widgets.yaml' }
        - { src: 'bookmarks.yaml', dest: '~/homepage/config/bookmarks.yaml' }
        - { src: 'proxmox.yaml', dest: '~/homepage/config/proxmox.yaml' }
        - { src: 'docker-compose.yaml', dest: '~/homepage/docker/docker-compose.yaml' }
        - { src: 'homepage.conf', dest: '/etc/nginx/conf.d/homepage.conf' }

    - name: copy binary file
      delegate_to: "{{ container_hostname }}"
      become: true
      copy:
        src: background.jpg
        dest: ~/homepage/images/background.jpg
        mode: '0755'

    # run container
    #
    - name: run homepage container
      delegate_to: "{{ container_hostname }}"
      become: true
      shell: |
        cd ~/homepage/docker
        docker compose up -d -y

    # add certificates and restart nginx
    #
    - import_tasks: ../ansible/add-ssl-certificate.yaml
      vars:
        sites: '-d {{ container_hostname }}.{{ domain_name }}'
        reloadcmd: 'sudo systemctl restart nginx'


    # add connection to local ssh config
    #
    - import_tasks: ../ansible/add-local-ssh-config.yaml
      vars:
        hostname: '{{ container_hostname }}'
        host: '{{ container_hostname }}'