services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ~/homepage/config:/app/config 
      - ~/homepage/images:/app/public/images
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: >
        {{ container_hostname }}.{{ domain_name }}