apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: otel-collector
  namespace: {{ app_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ otel_domain_name }}`) 
      services:
        - name: alloy
          port: 4318
    - kind: Rule
      match: Host(`{{ otel_domain_name }}`) && Header(`Content-Type`, `application/grpc`)
      services:
        - name: alloy
          port: 4317
          scheme: h2c
  tls: 
    secretName: '{{ app_name }}-tls'