apiVersion: v1
kind: Secret
metadata:
  name: cf-api-token
  namespace: cert-manager
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-dns
    cert-manager.io/acme-challenge-type: dns01
    cert-manager.io/dns01-provider: cloudflare
type: Opaque
stringData:
  api-token: '{{ cf_token }}'