apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: '{{ acme_server }}'
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: '{{ cf_email }}'
          apiTokenSecretRef:
            name: cf-api-token
            key: api-token