user  nginx;
worker_processes auto;
worker_rlimit_nofile 200000;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  16384;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}


## mod stream configuration
##
stream {

        log_format stream '$remote_addr - - [$time_local] $protocol '
                    '$status $bytes_sent $bytes_received '
                    '$upstream_addr "$ssl_preread_server_name" '
                    '"$ssl_preread_protocol" "$ssl_preread_alpn_protocols"';

        access_log /var/log/nginx/stream.log stream;
        error_log /var/log/nginx/stream.error.log;

        resolver 192.168.30.1 valid=30s;

        map $ssl_preread_server_name $upstream_map {

                default                 main; # must be first entry

                rspeed.bdgn.me          vless-reality;
                tspeed.bdgn.me          vless-tcp;
                xspeed.bdgn.me          vless-xhttp;
                
                speed.bdgn.me           speed;
                plex.bdgn.me            plex;
                ntfy.bdgn.me            ntfy;
                immich.bdgn.me          immich;
                s3.bdgn.me              s3;
                syncthing.bdgn.me       syncthing;
                ha.bdgn.me              homeassistant;
        }


        upstream main {
                server 127.0.0.1:20000; # default site
        }

        upstream vless-reality {
                server 127.0.0.1:20001;
        }

        upstream vless-tcp {
                server 127.0.0.1:20002; # vless-tcp -> speed or vpn
        }

        upstream vless-xhttp {
                server 127.0.0.1:20005; # vless-xhttp -> vpn
        }

        upstream speed {
                server 127.0.0.1:20006; # Speed server
        }

        upstream plex {
                server 192.168.20.212:443; # Plex media server
        }

        upstream ntfy {
                server 192.168.20.220:443; # ntfy.sh server
        }

        upstream immich {
                server 192.168.20.18:443; # immich server
        }

        upstream s3 {
                server 192.168.10.212:443; # S3 server
        }

        upstream syncthing {
                server 192.168.20.221:443; # Syncthing server
        }

        upstream homeassistant {
                server 192.168.40.204:443; # Home Assistant server
        }

        server {
                listen 443      reuseport;
                listen [::]:443 reuseport;
                proxy_pass      $upstream_map;
                ssl_preread     on;

                proxy_connect_timeout 10s;
                proxy_timeout 1h;
                proxy_socket_keepalive on;
                proxy_half_close on;
        }

        # qBittorrent port forward
        #
        server {
                listen 13779;
                proxy_pass      192.168.20.235:57684;
        }
}