zitadel:
  masterkey: {{ zitadel_masterkey }}
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: {{ auth_domain_name }}
    ExternalPort: 443
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: {{ pgi_host_rw }}
        Port: 5432
        Database: {{ zitadel_db_name }}
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: {{ pgi_user }}
          Password: {{ pgi_password }}
          SSL:
            Mode: disable
        Admin:
          Username: {{ pgi_user }}
          Password: {{ pgi_password }}
          ExistingDatabase: {{ zitadel_db_name }}
          SSL:
            Mode: disable
login:
  enabled: false

setupJob:
  machinekeyWriter:
    image:
      # repository можно не указывать, если он уже задан по умолчанию в chart’е
      # repository: alpine/k8s
      tag: "1.34.1"