- name: create lxc container
  hosts: 'prox-n2'
  gather_facts: false
  vars:
    proxmox_node        : "{{ inventory_hostname }}"
    proxmox_password    : "{{ ansible_password }}"
    container_ssh_file  : "{{ ssh_pub_key_file }}"
    container_hostname  : 'immich'
    container_vlan_id   : 20
    container_ip        : ''
    container_vmid      : 20307
    container_disk_size : 2
    container_memory    : 4096
    container_cores     : 2
    container_user      : 'root'
    container_nesting   : 1
    container_mount     : 'immich'
    container_host_mount: 'media/immich'
  tasks:

    # create basic container
    #
    - import_tasks: ../ansible/create-lxc.yaml

    # copy configs
    #
    - name: create config directory
      delegate_to: "{{ container_hostname }}"
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - ~/immich

  
    - name: copy configs
      delegate_to: "{{ container_hostname }}"
      become: true
      copy:
        dest: "{{ item.dest }}"
        force: true
        content: '{{ lookup("template", item.src) }}'
      with_items:
        - { src: 'generated.env', dest: '~/immich/.env' }
        - { src: 'docker-compose.yaml', dest: '~/immich/docker-compose.yaml' }

    # install docker and run immich
    #
    - name: install docker
      import_tasks: ../ansible/add-docker.yaml

    - name: run immich
      delegate_to: "{{ container_hostname }}"
      become: yes
      shell: |
        cd ~/immich
        docker compose up -d -y
            
    # Nginx
    # 
    - name: install nginx
      import_tasks: ../ansible/add-nginx-ubuntu.yaml

    - name: create nginx config
      delegate_to: "{{ container_hostname }}"
      copy:
        dest: /etc/nginx/conf.d/{{ container_hostname }}.conf
        content: "{{ lookup('template', 'nginx-immich.conf') }}"

    # add certificates and restart nginx
    #
    - import_tasks: ../ansible/add-ssl-certificate.yaml
      vars:
        sites: '-d {{ container_hostname }}.{{ domain_name }}'
        reloadcmd: 'sudo systemctl restart nginx'

    # add connection to local ssh config
    #
    - import_tasks: ../ansible/add-local-ssh-config.yaml
      vars:
        hostname: '{{ container_hostname }}'
        host: '{{ container_hostname }}'