apiVersion: v1
kind: Service
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
spec:
  ports:
  - name: http
    port: {{ app_port }}
    targetPort: http
  selector:
    {{ selectors | indent(4) }}