apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-forward-auth
  namespace: {{ app_namespace }}
spec:
  forwardAuth:
    address: "http://{{ app_name }}.{{ app_namespace }}:{{ app_port }}"
    authResponseHeaders:
      - "X-Auth-Request-User"
      - "X-Auth-Request-Email"
      - "Authorization"
    trustForwardHeader: true

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-auth-error
  namespace: {{ app_namespace }}
spec:
  errors:
    status:
      - "401-403"
    service:
      name: {{ app_name }}
      port: {{ app_port }}  
    query: /oauth2/start