apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers
  namespace: {{ app_namespace }}  
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: {{ auth_domain_name }}  
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ auth_domain_name }}`) && PathPrefix(`/oauth2`)
      kind: Rule
      middlewares:
        - name: auth-headers
          namespace: {{ app_namespace }}
      services:
        - name: {{ app_name }}
          port: {{ app_port }}
  tls: {}