
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ app_version }}
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    jvmOptions: 
      -Xms: 256m
      -Xmx: 512m
      
  entityOperator:
    topicOperator: {}
    userOperator: {}


## Test kafka
# kubectl exec kafka-kafka-node-pool-0 -n infrastructure -i -t -- bin/kafka-topics.sh \
#   --bootstrap-server kafka-kafka-brokers.infrastructure.svc:9092 \
#   --topic test \
#   --create \
#   --partitions 3 \
#   --replication-factor 1
#
# kubectl exec kafka-kafka-node-pool-0 -n infrastructure -i -t -- bin/kafka-console-producer.sh --bootstrap-server kafka-kafka-brokers.infrastructure.svc:9092 --topic test  
#
# kubectl exec kafka-kafka-node-pool-0 -n infrastructure -i -t -- bin/kafka-console-consumer.sh --bootstrap-server kafka-kafka-brokers.infrastructure.svc:9092 --topic test  
