## Ansible Playbook to setup Proxmox Node
##
## Usage: ansible-playbook -i ansible/inventory.secret.yaml node/node-setup.yaml 
##
## Variables:
## - node_id: unique id for the node (used for ip and other settings)
## - ansible_ssh_private_key_file: path to ssh private key file
## - ansible_user: ssh user
## - ssh_pub_key_file: path to ssh public key file
## - domain_name: domain name for the node
##
## Steps performed:
## - Correct Proxmox VE sources and disable subscription nag
## - Update system
## - Setup ssh login with certificate
## - Install iperf3, btop, lldpd (frr removed as proxmox 9 has it built in)
## - Create thunderbolt network
## - Add intel & quemu on grub
## - Setup local ssh config
## - Reboot node

- name: run post install script
  hosts: all
  become: yes
  tasks:
    - name: Correcting Debian Sources
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/debian.sources
        content: |
          Types: deb
          URIs: http://deb.debian.org/debian/
          Suites: trixie trixie-updates
          Components: main contrib non-free-firmware
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
          Enabled: false

          Types: deb
          URIs: http://security.debian.org/debian-security/
          Suites: trixie-security
          Components: main contrib non-free-firmware
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
          Enabled: false

          Types: deb
          URIs: http://deb.debian.org/debian/
          Suites: trixie trixie-updates
          Components: main contrib 
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
          Enabled: true

          Types: deb
          URIs: http://security.debian.org/debian-security/
          Suites: trixie-security
          Components: main contrib
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
          Enabled: true

    - name: Correcting Proxmox VE Sources
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/proxmox.sources
        content: |
          Types: deb
          URIs: http://download.proxmox.com/debian/pve
          Suites: trixie
          Components: pve-no-subscription
          Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg          

    - name: Correct ceph package sources
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/ceph.sources
        content: |
          Types: deb
          URIs: https://enterprise.proxmox.com/debian/ceph-squid
          Suites: trixie
          Components: enterprise
          Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
          Enabled: false

          Types: deb
          URIs: http://download.proxmox.com/debian/ceph-squid
          Suites: trixie
          Components: no-subscription
          Enabled: true

    - name: Disable enterprise repo
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.sources
        regexp: '^Enabled='
        line: 'Enabled: false'

    - name: Removing subscription nag from UI
      ansible.builtin.lineinfile:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: "^.*res.data.status.toLowerCase.{2} !== 'active'.*"
        line: "res.data.status.toLowerCase() === 'no'"


- name: update system
  hosts: all
  become: yes
  tasks:
    - name: update system
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

- name: make ssh login with ceritificate
  hosts: all
  become: yes
  tasks:
    - name: make ssh login with ceritificate
      authorized_key: user={{ ansible_user }} key="{{ lookup('file', '{{ ssh_pub_key_file }}') }}"

- name: install iperf3, btop, lldpd #, frr
  hosts: all
  become: yes
  tasks:
    - name: install stuff
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - iperf3
        - btop
        - lldpd
        - s3fs
        #- frr

- name: create thunderbolt network
  hosts: all
  become: yes
  tasks:
    - name: add thunderbolt modules
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "{{ item.line }}"
      loop:
        - line: thunderbolt
        - line: thunderbolt-net

    - name: create link thunderbolt files to rename interfaces
      ansible.builtin.copy:
        dest: /etc/systemd/network/00-thunderbolt{{ item.id }}.link
        content: |
          [Match]
          Path={{ item.pci_path }}
          Driver=thunderbolt-net
          [Link]
          MACAddressPolicy=none
          Name={{ item.if_name }}
      loop:
        - { id: 0, pci_path: "pci-0000:00:0d.2", if_name: "en05" }
        - { id: 1, pci_path: "pci-0000:00:0d.3", if_name: "en06" }

    - name: make tb interface up on reload
      ansible.builtin.copy:
        dest: /etc/udev/rules.d/10-tb-en.rules
        content: |
          ACTION=="add|move", SUBSYSTEM=="net", KERNEL=="en05", RUN+="/usr/local/bin/pve-en05.sh"
          ACTION=="add|move", SUBSYSTEM=="net", KERNEL=="en06", RUN+="/usr/local/bin/pve-en06.sh"

    - name: create iface up scripts
      ansible.builtin.copy:
        dest: /usr/local/bin/pve-{{ item.line }}.sh
        content: |
          #! /bin/bash
          # this brings the renamed interface up and reprocesses any settings in /etc/network/interfaces for the renamed interface
          # /usr/sbin/ifup {{ item.line }}

          LOGFILE="/var/log/udev-debug.log"
          echo "$(date): {{ item.line }} bringup triggered" >> "$LOGFILE"
          for i in {1..5}; do
              if ip link set {{ item.line }} up mtu 65520; then
                  echo "$(date): {{ item.line }} up successful on attempt $i" >> "$LOGFILE"
                  break
              else
                  echo "$(date): Attempt $i failed, retrying in 3 seconds..." >> "$LOGFILE"
                  sleep 3
              fi
          done

      loop:
        - line: en05
        - line: en06

    - name: make scripts executable
      ansible.builtin.command:
        cmd: chmod +x /usr/local/bin/pve-en05.sh /usr/local/bin/pve-en06.sh

    - name: update initramfs
      ansible.builtin.command:
        cmd: update-initramfs -u -k all

    - name: rewrite network interfaces
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        content: |
          # network interface settings; autogenerated
          # Please do NOT modify this file directly, unless you know what
          # you're doing.
          #
          # If you want to manage parts of the network configuration manually,
          # please utilize the 'source' or 'source-directory' directives to do
          # so.
          # PVE will preserve these directives, but will NOT read its network
          # configuration from sourced files, so do not attempt to move any of
          # the PVE managed interfaces into external files!

          auto lo
          iface lo inet loopback

          iface enp86s0 inet manual

          auto en05
          iface en05 inet manual
                  mtu 65520

          auto en06
          iface en06 inet manual
                  mtu 65520

          auto vmbr0
          iface vmbr0 inet static
                  address 192.168.10.24{{ node_id }}/24
                  gateway 192.168.10.1
                  bridge-ports enp86s0
                  bridge-stp off
                  bridge-fd 0
                  bridge-vlan-aware yes
                  bridge-vids 2-100

          iface wlo1 inet manual

          source /etc/network/interfaces.d/*

# auto vmbr1
# iface vmbr1 inet6 static
#         address fd50::1/120
#         bridge-ports none
#         bridge-stp off
#         bridge-fd 0
      
    - name: enable systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: enable ip v4 & v6 forwarding
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-sysctl.conf
        content: |
          net.ipv4.ip_forward=1
          net.ipv6.conf.all.forwarding=1

    - name: create thunderbolt startup service
      ansible.builtin.copy:
        dest: /etc/systemd/system/thunderbolt-interfaces.service
        content: |
          [Unit]
          Description=Configure Thunderbolt Network Interfaces
          After=network.target thunderbolt.service
          Wants=network.target

          [Service]
          Type=oneshot
          RemainAfterExit=yes
          ExecStart=/usr/local/bin/thunderbolt-startup.sh

          [Install]
          WantedBy=multi-user.target

    - name: create thunderbolt startup script
      ansible.builtin.copy:
        dest: /usr/local/bin/thunderbolt-startup.sh
        content: |
          #!/bin/bash
          # Thunderbolt interface startup script
          LOGFILE="/var/log/thunderbolt-startup.log"

          echo "$(date): Starting Thunderbolt interface configuration" >> "$LOGFILE"

          # Wait up to 30 seconds for interfaces to appear
          for i in {1..30}; do
              if ip link show en05 &>/dev/null && ip link show en06 &>/dev/null; then
                  echo "$(date): Thunderbolt interfaces found" >> "$LOGFILE"
                  break
              fi
              echo "$(date): Waiting for Thunderbolt interfaces... ($i/30)" >> "$LOGFILE"
              sleep 1
          done

          # Configure interfaces if they exist
          if ip link show en05 &>/dev/null; then
              /usr/local/bin/pve-en05.sh
              echo "$(date): en05 configured" >> "$LOGFILE"
          fi

          if ip link show en06 &>/dev/null; then
              /usr/local/bin/pve-en06.sh
              echo "$(date): en06 configured" >> "$LOGFILE"
          fi

          echo "$(date): Thunderbolt configuration completed" >> "$LOGFILE"

    - name: make scripts executable
      ansible.builtin.command:
        cmd: chmod +x /usr/local/bin/thunderbolt-startup.sh

    - name: enable thunderbolt startup service
      ansible.builtin.systemd:
        name: thunderbolt-interfaces.service
        enabled: yes
        state: started


    # - name: Create a directory for frr service if it does not exist
    #   ansible.builtin.file:
    #     path: /etc/systemd/system/frr.service.d
    #     state: directory

    # - name: create dependency file for FRR to start after network
    #   ansible.builtin.copy:
    #     content: |
    #       [Unit]
    #       Wants=sys-subsystem-net-devices-en05.device sys-subsystem-net-devices-en06.device
    #       After=sys-subsystem-net-devices-en05.device sys-subsystem-net-devices-en06.device
    #     dest: /etc/systemd/system/frr.service.d/dependencies.conf

    # - name: enable frr daemon
    #   ansible.builtin.replace:
    #     path: /etc/frr/daemons
    #     regexp: 'fabricd=no'
    #     replace: 'fabricd=yes'

    # - name: write frr config
    #   ansible.builtin.copy:
    #     content: |
    #       frr version 8.5.2
    #       frr defaults traditional
    #       hostname {{ inventory_hostname }}
    #       log syslog informational
    #       service integrated-vtysh-config
    #       !
    #       interface en05
    #         ipv6 router openfabric 1
    #       exit
    #       !
    #       interface en06
    #         ipv6 router openfabric 1
    #       exit
    #       !
    #       interface lo
    #         ipv6 router openfabric 1
    #         openfabric passive
    #       exit
    #       !
    #       router openfabric 1
    #         net 49.0000.0000.000{{ node_id }}.00
    #       exit
    #       !
    #     dest: /etc/frr/frr.conf


    - name: Attach tb ports to perf cpu
      ansible.builtin.cron:
        name: "set tb ports to perf cpu"
        special_time: reboot
        job: grep thunderbolt /proc/interrupts | cut -d ":" -f1 | xargs -I {} sh -c 'echo 0-7 | tee "/proc/irq/{}/smp_affinity_list"'


- name: Add intel & quemu on grub
  hosts: all
  become: yes
  tasks:
    - name: Check if we fix grub already
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX_DEFAULT=".*intel_iommu=on.*"'
        state: absent
      check_mode: yes
      changed_when: false
      register: out

    - name: Add intel & quemu on grub
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
        replace: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on iommu=pt"'
      when: not out.found

    - name: update grub
      become: yes
      ansible.builtin.command: update-grub
      when: not out.found

## Setup local ssh config
##
- name: update local ssh config
  hosts: all
  vars:
    text_block: |
      Host {{ inventory_hostname }}
        HostName {{ ansible_host }}
        User root
        Port 22
        IdentityFile {{ ansible_ssh_private_key_file }}
        IdentitiesOnly yes

  tasks:
    - name: update local ssh config
      blockinfile:
        path: ~/.ssh/config
        append_newline: true
        prepend_newline: true
        insertbefore: "Host \\*"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        marker_begin: "{{ node_id }}"  
        block: "{{ text_block }}"
        create: yes  # Create file if it doesn't exist
      delegate_to: localhost


- name: Node reboot
  hosts: all
  become: yes
  tasks:
    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
        test_command: uptime
