apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: {{ app_namespace }}
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ minio_root_user }}"
    export MINIO_ROOT_PASSWORD="{{ minio_root_password }}"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
    export CONSOLE_TLS_ENABLE="on"
    export MINIO_IDENTITY_OPENID_CONFIG_URL="https://{{ auth_domain_name }}/.well-known/openid-configuration"
    export MINIO_IDENTITY_OPENID_CLIENT_ID="{{ zitadel_minio_id }}"
    export MINIO_IDENTITY_OPENID_CLIENT_SECRET="{{ zitadel_minio_secret }}"
    export MINIO_IDENTITY_OPENID_CLAIM_NAME="policy"
    export MINIO_IDENTITY_OPENID_DISPLAY_NAME="Zitadel"
    export MINIO_IDENTITY_OPENID_CLAIM_PREFIX=""
    export MINIO_IDENTITY_OPENID_REDIRECT_URI="https://{{ domain_fqdn }}/minio/oauth_callback"
    export MINIO_IDENTITY_OPENID_SCOPES="openid,profile,email"
    export MINIO_IDENTITY_OPENID_COMMENT="Zitadel"
    export MINIO_IDENTITY_OPENID_CLAIM_USERINFO="on"
    export MINIO_PROMETHEUS_AUTH_TYPE="public"
type: Opaque