apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
  labels:
    {{ labels | indent(4) }}
spec:
  features:
    ## Specify a list of domains used to access MinIO and Console
    domains:
      # minio:
      #   - {{ s3_domain_name }}
      console: 'https://{{ main_domain_name }}/minio/'
      
  requestAutoCert: false
  configuration:
    name: storage-configuration
  image: quay.io/minio/minio:RELEASE.2025-04-03T14-56-28Z
  mountPath: /export
  pools:
    - name: minio-pool
      servers: 3
      volumesPerServer: 2
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ minio_storage_size }}         
          storageClassName: {{ minio_storage_class_name }}

  users:
    - name: storage-user

  buckets:
    - name: "loki"
      region: "us-east-1"
      objectLock: false
    - name: "tempo"
      objectLock: false

  #prometheusOperator: true

    


