apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-minio
  namespace: {{ app_namespace }}
spec:
  stripPrefix:
    prefixes:
      - "/minio"

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: '{{ app_name }}' #-console
  namespace: {{ app_namespace }}
spec:
  entryPoints:
    - websecure  # Use HTTPS entry point

  routes:
    - match: Host(`{{ main_domain_name }}`) && PathPrefix(`/minio`)
      kind: Rule
      middlewares:
        - name: strip-minio
      services:
        - name: '{{ app_name }}-console'
          port: 9090
          namespace: {{ app_namespace }}
  tls: {}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: '{{ app_name}}-api'
  namespace: {{ app_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ s3_domain_name }}`)
      kind: Rule
      services: 
        - name: {{ app_name }}
          port: 80
  tls: {}