apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-forwarded-proto-header
  namespace: {{ app_namespace }}
spec:
  headers:
    customRequestHeaders:
      x-forwarded-proto: https
---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ app_name }}
  namespace: {{ app_namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ auth_domain_name }}`)
      kind: Rule
      middlewares:
        - name: add-forwarded-proto-header
          namespace: {{ app_namespace }}
      services:
        - name: {{ app_name }}
          port: 8080
          scheme: h2c
          passHostHeader: true
          namespace: {{ app_namespace }}
  tls: {}