apiVersion: v1
kind: Secret
metadata:
  name: {{ pgi_secret_name }}
  namespace: {{ app_namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ pgi_user | b64encode }}
  password: {{ pgi_password | b64encode }}