apiVersion: v1
kind: Secret
metadata:
  name: {{ pg_secret_name }}
  namespace: {{ app_namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ pg_user | b64encode }}
  password: {{ pg_password | b64encode }}