apiVersion: v1
kind: Secret
metadata:
  name: az-secret
  namespace: {{ app_namespace }}
type: Opaque
data:
  az_sas_token: {{ az_sas_token | b64encode }}
  az_storage_account: {{ az_storage_account | b64encode }}