apiVersion: v1
kind: Secret
metadata:
  name: {{ aws_secret_name }}
  namespace: {{ app_namespace }}
type: Opaque
data:
  aws_key_id: {{ aws_key_id | b64encode }}
  aws_secret_key: {{ aws_secret_key | b64encode }}