apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: '{{ pgi_name }}-scheduled-backup'
  namespace: {{ app_namespace }}
spec:
  # Daily backup at midnight
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: {{ pgi_name }}
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
