apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ pgi_name }}
  namespace: {{ app_namespace }}
spec:

  instances: 3

  superuserSecret:
    name: {{ pgi_secret_name }}

  # PostgreSQL configuration
  postgresql:
    parameters:
      # Storage is local so we can optimize for local disk performance
      random_page_cost: "1.3"

  # Use barman-cloud plugin for backups
  #
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: false
      parameters:
        barmanObjectName: aws-inf-store

{% if s3_pgi_backup | length > 0 %}
  externalClusters:
    - name: {{ pgi_name }}
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: aws-inf-store
          serverName: {{ pgi_name }}
{% endif %}
{% if s3_pgi_backup | length > 0 %}
  bootstrap:
    recovery:
      source: {{ pgi_name }}
{% else %}
  bootstrap:
    initdb:
      database: {{ zitadel_db_name }}
      secret:
        name: {{ pgi_secret_name }}

    initdb:
      database: grafana
      secret:
        name: {{ pgi_secret_name }}
{% endif %}

  storage:
    storageClass: {{ pg_storage_class_name }}
    size: {{ pgi_storage_size }}

  # Pod distribution - ensure PostgreSQL instances are on different nodes
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname