apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ pg_name }}-restore'
  namespace: {{ app_namespace }}
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: '{{ pg_name }}-restore-isplit'
          image: ilaverlin/pg-az-backup:latest
          env:
          - name: POSTGRES_HOST
            value: '{{ pg_name }}-rw'
          - name: POSTGRES_DATABASE
            value: isplitapp
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ pg_secret_name }}
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ pg_secret_name }}
                key: password
          - name: AZURE_STORAGE_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: az-secret
                key: az_storage_account
          - name: AZURE_SAS
            valueFrom:
              secretKeyRef:
                name: az-secret
                key: az_sas_token
          - name: AZURE_CONTAINER_NAME
            value: 'pg-backup-isplit'
          - name: RESTORE
            value: "yes"
          - name: DROP_PUBLIC
            value: "create" 
      initContainers:
        - name: wait-postrges
          image: ilaverlin/pg-client:latest
          command: ['sh', '-c', "until pg_isready -h {{ pg_name }}-rw -p 5432; do  echo waiting for pg-server; sleep 5; done"]            