# TLS Store
# Should be in default namespace and name should be known for cert-manager
#
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
spec:
  defaultCertificate:
    secretName: {{ tls_secret_name }}