apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ app_namespace }}
  labels:
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  url: https://{{ main_domain_name }}/argocd
  oidc.config: |
    name: Zitadel
    issuer: https://{{ auth_domain_name }}
    clientID: "{{ zitadel_argocd_id }}"
    clientSecret: "{{ zitadel_argocd_secret }}"
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    logoutURL: https://{{ auth_domain_name }}/oidc/v1/end_session

  # add an additional local user with apiKey and login capabilities
  #   apiKey - allows generating API keys
  #   login - allows to login using UI
  accounts.alice: apiKey, login
  
  # disables user. User is enabled by default
  accounts.alice.enabled: "true"



