apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
   # Value for base href in index.html. Used if Argo CD is running behind reverse proxy under subpath different from / (default "/")
  server.basehref: "/argocd"
  # Used if Argo CD is running behind reverse proxy under subpath different from /
  server.rootpath: "/argocd"